export const products = [
    { productname: 'Beta-Malt', price: '6.00', category: 'Drinks' },
    { productname: 'Bel-Cola', price: '3.00', category: 'Drinks' },
    { productname: 'Choco-Malt', price: '5.00', category: 'Drinks' },
    { productname: '5 star(Sm)', price: '2.00', category: 'Drinks' },
    { productname: 'Guiness Malt', price: '7.00', category: 'Drinks' },
    { productname: 'Kallypo', price: '5.00', category: 'Drinks' },
    { productname: 'Planet', price: '3.00', category: 'Drinks' },
    { productname: 'Royal Apple', price: '4.00', category: 'Drinks' },
    { productname: 'Rush', price: '5.00', category: 'Drinks' },
    { productname: 'Special Apple', price: '3.00', category: 'Drinks' },
    { productname: 'Special Grapes', price: '3.00', category: 'Drinks' },
    { productname: 'Storm(B)', price: '6.00', category: 'Drinks' },
    { productname: 'Storm (Sm)', price: '4.00', category: 'Drinks' },
    { productname: 'Tamarinda', price: '3.00', category: 'Drinks' },
    { productname: 'U-Fresh', price: '5.00', category: 'Drinks' },
    { productname: 'Aqualis', price: '5.00', category: 'Detergents' },
    { productname: 'Athena', price: '4.50', category: 'Detergents' },
    { productname: 'Ama[Omo]', price: '2.00', category: 'Detergents' },
    { productname: 'Carbolic', price: '5.00', category: 'Detergents' },
    { productname: 'Geisha', price: '10.00', category: 'Detergents' },
    { productname: 'GFJ[Omo]', price: '2.00', category: 'Detergents' },
    { productname: 'Kleesoft(big)', price: '6.50', category: 'Detergents' },
    { productname: 'Kleesoft(s)', price: '3.50', category: 'Detergents' },
    { productname: 'Kleesoft[Omo]', price: '4.50', category: 'Detergents' },
    { productname: 'Kenta(s)', price: '3.50', category: 'Detergents' },
    { productname: 'Madar', price: '6.50', category: 'Detergents' },
    { productname: 'Madar(s)', price: '3.50', category: 'Detergents' },
    { productname: 'Madar[Omo]', price: '4.50', category: 'Detergents' },
    { productname: 'Magico', price: '7.00', category: 'Detergents' },
    { productname: 'Medisoft', price: '8.00', category: 'Detergents' },
    { productname: 'Obolo', price: '10.00', category: 'Detergents' },
    { productname: 'Oro', price: '7.00', category: 'Detergents' },
    { productname: 'So Kleen', price: '2.00', category: 'Detergents' },
    { productname: 'Perla', price: '4.00', category: 'Detergents' },
    { productname: 'Saba', price: '6.50', category: 'Detergents' },
    { productname: 'Abena rice', price: 'Price', category: 'Eatables' },
    { productname: 'African Queen', price: 'Price', category: 'Eatables' },
    { productname: 'Classic  rice', price: 'Price', category: 'Eatables' },
    { productname: 'Delight rice', price: 'Price', category: 'Eatables' },
    { productname: 'Ena Pa', price: 'Price', category: 'Eatables' },
    { productname: 'Rice-broken{1 cup,half} Rice-full{1 cup, half}', price: 'Price Price', category: 'Eatables' },
    { productname: 'Sardine', price: 'Price', category: 'Eatables' },
    { productname: 'Digestive', price: 'Price', category: 'Appetizers' },
    { productname: 'GMG', price: 'Price', category: 'Appetizers' },
    { productname: 'Heart', price: 'Price', category: 'Appetizers' },
    { productname: 'Milky magic biscuits', price: 'Price', category: 'Appetizers' },
    { productname: 'Royal King Cracker biscuit (big)', price: 'Price', category: 'Appetizers' },
    { productname: 'Royal King Cracker biscuit (small)', price: 'Price', category: 'Appetizers' },
    { productname: 'Simply good biscuit', price: 'Price', category: 'Appetizers' },
    { productname: 'Pro Small Brush', price: 'Price', category: 'Sanitories' },
    { productname: 'Pampers', price: 'Price', category: 'Sanitories' },
    { productname: 'VIP brush', price: 'Price', category: 'Sanitories' },
    { productname: 'Yazz brush', price: 'Price', category: 'Sanitories' },
    { productname: 'Yazz pad', price: 'Price', category: 'Sanitories' },
  ];
  
  